name       : kgamma5
version    : 5.12.3
release    : 13
source     :
    - https://cdn.download.kde.org/stable/plasma/5.12.3/kgamma5-5.12.3.tar.xz : 7557d74a7159a9a7e344223ddb0f475e54f6b8d73cfb90e5acbd4b289e237b5b
license    : GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : Adjust your monitor's gamma settings
description: |
    Adjust your monitor's gamma settings.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - pkgconfig(x11)
    - extra-cmake-modules
    - kconfig-devel
    - kconfigwidgets-devel
    - kdelibs4support-devel
    - kdoctools-devel
    - ki18n-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
