name       : kgamma5
version    : 5.18.1
release    : 44
source     :
    - https://cdn.download.kde.org/stable/plasma/5.18.1/kgamma5-5.18.1.tar.xz : 370cdf9988a57509f3df395e1cc6f78505da171c18b3338cb57bfd7f7e230658
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : Adjust your monitor's gamma settings
description: |
    Adjust your monitor's gamma settings.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(x11)
    - extra-cmake-modules
    - kconfigwidgets-devel
    - kdoctools-devel
    - ki18n-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
