name       : kgamma5
version    : 5.14.3
release    : 26
source     :
    - https://cdn.download.kde.org/stable/plasma/5.14.3/kgamma5-5.14.3.tar.xz : 986ca88140541279b8ae152d13ae33793df6d5787ddafb43c065dac5a231280f
license    : GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : Adjust your monitor's gamma settings
description: |
    Adjust your monitor's gamma settings.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(x11)
    - extra-cmake-modules
    - kconfig-devel
    - kconfigwidgets-devel
    - kdelibs4support-devel
    - kdoctools-devel
    - ki18n-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
