name       : kgamma5
version    : 5.27.4
release    : 84
source     :
    - https://cdn.download.kde.org/stable/plasma/5.27.4/kgamma5-5.27.4.tar.xz : 4a81c50b7f96b5a6f0e60b58a1d38fc375f445595e2e349e692d4c40d8355802
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-2.0-or-later
component  : desktop.kde.core
summary    : Adjust your monitor's gamma settings
description: |
    Adjust your monitor's gamma settings.
optimize   : lto
builddeps  :
    - pkgconfig(xxf86vm)
    - kconfigwidgets-devel
    - kdoctools-devel
    - ki18n-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc
