name       : kgamma5
version    : 5.17.4
release    : 42
source     :
    - https://cdn.download.kde.org/stable/plasma/5.17.4/kgamma5-5.17.4.tar.xz : ab8cd07b519816a6ccb316cebece2381232e113bdb22007535950f8324f5f398
license    : GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : Adjust your monitor's gamma settings
description: |
    Adjust your monitor's gamma settings.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(x11)
    - extra-cmake-modules
    - kconfigwidgets-devel
    - kdoctools-devel
    - ki18n-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
