name       : kgamma5
version    : 5.18.5
release    : 48
source     :
    - https://cdn.download.kde.org/stable/plasma/5.18.5/kgamma5-5.18.5.tar.xz : 3aa89e361646214fb4910409644b941c83a85505d3d8a1d37984598d3e54269f
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : Adjust your monitor's gamma settings
description: |
    Adjust your monitor's gamma settings.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(x11)
    - extra-cmake-modules
    - kconfigwidgets-devel
    - kdoctools-devel
    - ki18n-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
