name       : kgamma5
version    : 5.12.0
release    : 10
source     :
    - https://cdn.download.kde.org/stable/plasma/5.12.0/kgamma5-5.12.0.tar.xz : 523767048e98ceaeb7425409f692fb60a53e2e56ca8b2a99cf6fc2442c7baded
license    : GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : Adjust your monitor's gamma settings
description: |
    Adjust your monitor's gamma settings.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - pkgconfig(x11)
    - extra-cmake-modules
    - kconfig-devel
    - kconfigwidgets-devel
    - kdelibs4support-devel
    - kdoctools-devel
    - ki18n-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
