name       : kgamma5
version    : 5.15.2
release    : 29
source     :
    - https://cdn.download.kde.org/stable/plasma/5.15.2/kgamma5-5.15.2.tar.xz : 5ea3d42ede065b71de0e015d76c42fe8fbb930e390c7041c5be0e16d1b10171b
license    : GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : Adjust your monitor's gamma settings
description: |
    Adjust your monitor's gamma settings.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(x11)
    - extra-cmake-modules
    - kconfig-devel
    - kdelibs4support-devel
    - ki18n-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
