name       : kgamma5
version    : 5.13.2
release    : 18
source     :
    - https://cdn.download.kde.org/stable/plasma/5.13.2/kgamma5-5.13.2.tar.xz : d2d87daf4cf35857e263e953adcc04d8d5165adb5d3795bcfdbe3ce51f877e34
license    : GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : Adjust your monitor's gamma settings
description: |
    Adjust your monitor's gamma settings.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - pkgconfig(x11)
    - extra-cmake-modules
    - kconfig-devel
    - kconfigwidgets-devel
    - kdelibs4support-devel
    - kdoctools-devel
    - ki18n-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
