name       : kgamma5
version    : 5.17.2
release    : 40
source     :
    - https://cdn.download.kde.org/stable/plasma/5.17.2/kgamma5-5.17.2.tar.xz : fca731f2abc82566ec5f15d697171de00efe74c0b44a414787724246bd5adf5c
license    : GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : Adjust your monitor's gamma settings
description: |
    Adjust your monitor's gamma settings.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(x11)
    - extra-cmake-modules
    - kconfigwidgets-devel
    - kdoctools-devel
    - ki18n-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
