name       : kgamma5
version    : 5.19.3
release    : 50
source     :
    - https://cdn.download.kde.org/stable/plasma/5.19.3/kgamma5-5.19.3.tar.xz : 918f4e0146f088d96bea87f7c8b3842633680c816b82a3070831d5b2d492bd94
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : Adjust your monitor's gamma settings
description: |
    Adjust your monitor's gamma settings.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(xxf86vm)
    - extra-cmake-modules
    - kconfigwidgets-devel
    - kdoctools-devel
    - ki18n-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc/HTML
