name       : kgamma5
version    : 5.22.2
release    : 66
source     :
    - https://cdn.download.kde.org/stable/plasma/5.22.2.1/kgamma5-5.22.2.1.tar.xz : 71998d89a63074828998aee515f3cc50f1d014b220d58e0ff58ff113b6cbf5c0
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-2.0-or-later
component  : desktop.kde.core
summary    : Adjust your monitor's gamma settings
description: |
    Adjust your monitor's gamma settings.
optimize   : lto
builddeps  :
    - pkgconfig(xxf86vm)
    - kconfigwidgets-devel
    - kdoctools-devel
    - ki18n-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc
