name       : kgamma5
version    : 5.27.7
release    : 87
source     :
    - https://cdn.download.kde.org/stable/plasma/5.27.7/kgamma5-5.27.7.tar.xz : d45e88d4ee1c6cffa0b5ef085c4a7d028ade37e2daa72253e74941d9bcf5ae6c
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-2.0-or-later
component  : desktop.kde.core
summary    : Adjust your monitor's gamma settings
description: |
    Adjust your monitor's gamma settings.
optimize   : lto
builddeps  :
    - pkgconfig(xxf86vm)
    - kconfigwidgets-devel
    - kdoctools-devel
    - ki18n-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc
