name       : kgamma5
version    : 5.19.2
release    : 49
source     :
    - https://cdn.download.kde.org/stable/plasma/5.19.2/kgamma5-5.19.2.tar.xz : 976d2e19bc23929e38f1f702275b943ae15b839cddcc540bebd05e854cb4fcfc
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : Adjust your monitor's gamma settings
description: |
    Adjust your monitor's gamma settings.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(xxf86vm)
    - extra-cmake-modules
    - kconfigwidgets-devel
    - kdoctools-devel
    - ki18n-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
