name       : kgamma5
version    : 5.14.1
release    : 24
source     :
    - https://cdn.download.kde.org/stable/plasma/5.14.1/kgamma5-5.14.1.tar.xz : 0085732017dad39afddbe303c7e30fc971f6abb281e3bfa90b33411b7f7fb68b
license    : GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : Adjust your monitor's gamma settings
description: |
    Adjust your monitor's gamma settings.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(x11)
    - extra-cmake-modules
    - kconfig-devel
    - kconfigwidgets-devel
    - kdelibs4support-devel
    - kdoctools-devel
    - ki18n-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
