name       : kgamma5
version    : 5.12.1
release    : 11
source     :
    - https://cdn.download.kde.org/stable/plasma/5.12.1/kgamma5-5.12.1.tar.xz : 6b625b5316d7ac31c11d12ebd2ce683e63689b67db7dd0098ca074b008cbf331
license    : GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : Adjust your monitor's gamma settings
description: |
    Adjust your monitor's gamma settings.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - pkgconfig(x11)
    - extra-cmake-modules
    - kconfig-devel
    - kconfigwidgets-devel
    - kdelibs4support-devel
    - kdoctools-devel
    - ki18n-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
