name       : kgamma5
version    : 5.25.3
release    : 80
source     :
    - https://cdn.download.kde.org/stable/plasma/5.25.3/kgamma5-5.25.3.tar.xz : a03e0fc48be83799fad555576c85b45072a8e42863ca68741a0ca5750d04e580
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-2.0-or-later
component  : desktop.kde.core
summary    : Adjust your monitor's gamma settings
description: |
    Adjust your monitor's gamma settings.
optimize   : lto
builddeps  :
    - pkgconfig(xxf86vm)
    - kconfigwidgets-devel
    - kdoctools-devel
    - ki18n-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc
