name       : kgamma5
version    : 5.12.2
release    : 12
source     :
    - https://cdn.download.kde.org/stable/plasma/5.12.2/kgamma5-5.12.2.tar.xz : 5af6295fb3fa43a802bd737f06f2159e8c379f2260c8bd3022aea402784316f6
license    : GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : Adjust your monitor's gamma settings
description: |
    Adjust your monitor's gamma settings.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - pkgconfig(x11)
    - extra-cmake-modules
    - kconfig-devel
    - kconfigwidgets-devel
    - kdelibs4support-devel
    - kdoctools-devel
    - ki18n-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
