name       : kgamma5
version    : 5.11.0
release    : 4
source     :
    - https://download.kde.org/stable/plasma/5.11.0/kgamma5-5.11.0.tar.xz : ee92121dcb1b2ea4730b7ff917e14c252a11486dffc545bb817b35d8f4a71d2d
license    : GPL-2.0
component  : desktop.kde.core
summary    : Adjust your monitor's gamma settings
description: |
    Adjust your monitor's gamma settings.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - pkgconfig(x11)
    - extra-cmake-modules
    - kconfig-devel
    - kconfigwidgets-devel
    - kdelibs4support-devel
    - kdoctools-devel
    - ki18n-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
