name       : kgamma5
version    : 5.16.3
release    : 36
source     :
    - https://cdn.download.kde.org/stable/plasma/5.16.3/kgamma5-5.16.3.tar.xz : 7b609d418e670bdc75d6c2894255088aab6a7a2005afe3ec99348a49d67eb61d
license    : GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : Adjust your monitor's gamma settings
description: |
    Adjust your monitor's gamma settings.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(x11)
    - extra-cmake-modules
    - kconfig-devel
    - kdelibs4support-devel
    - ki18n-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
