name       : kgamma5
version    : 5.11.1
release    : 5
source     :
    - https://cdn.download.kde.org/stable/plasma/5.11.1/kgamma5-5.11.1.tar.xz : cd6f3c3074dbf3da4418d1a57dd287f9da08b9d37c3a21ab8c7ff8627f5735d5
license    : GPL-2.0
component  : desktop.kde.core
summary    : Adjust your monitor's gamma settings
description: |
    Adjust your monitor's gamma settings.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - pkgconfig(x11)
    - extra-cmake-modules
    - kconfig-devel
    - kconfigwidgets-devel
    - kdelibs4support-devel
    - kdoctools-devel
    - ki18n-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
