name       : kgamma5
version    : 5.15.5
release    : 32
source     :
    - https://download.kde.org/stable/plasma/5.15.5/kgamma5-5.15.5.tar.xz : 5e5d2dd439d4fd298eb0283fd9f2bad009c5efe22f72aea795138d22adfdc1e7
license    : GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : Adjust your monitor's gamma settings
description: |
    Adjust your monitor's gamma settings.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(x11)
    - extra-cmake-modules
    - kconfig-devel
    - kdelibs4support-devel
    - ki18n-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
